import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { buildClassesPackFromText } from '../src/rules/classes/parse/parseClassesTxt';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '../../..');

const envPathRaw = process.env.CLASSES_TXT_PATH?.trim();
const envPath = envPathRaw ? path.resolve(envPathRaw) : null;
const fallbackPath = path.resolve(repoRoot, 'dnd5e_classes_subclasses.txt');

const indexOutputPath = path.resolve(repoRoot, 'apps/web/src/rules/classes/generated/classesIndex.ts');
const detailsOutputDir = path.resolve(repoRoot, 'apps/web/public/rules/classes/entries');

const resolveInputPath = (): string => {
  if (envPath) {
    return envPath;
  }

  return fallbackPath;
};

const clearDirectoryJsonFiles = (directoryPath: string): void => {
  if (!existsSync(directoryPath)) {
    return;
  }

  const entries = readdirSync(directoryPath, {
    withFileTypes: true
  });
  for (const entry of entries) {
    const fullPath = path.join(directoryPath, entry.name);
    if (entry.isDirectory()) {
      clearDirectoryJsonFiles(fullPath);
      continue;
    }

    if (entry.isFile() && entry.name.toLowerCase().endsWith('.json')) {
      rmSync(fullPath, {
        force: true
      });
    }
  }
};

const loadSpellSlugMap = async (): Promise<Map<string, string>> => {
  const output = new Map<string, string>();
  const spellIndexModulePath = path.resolve(
    repoRoot,
    'apps/web/src/rules/spells/generated/spellNameIndex.ts'
  );
  if (!existsSync(spellIndexModulePath)) {
    return output;
  }

  try {
    const moduleUrl = pathToFileURL(spellIndexModulePath).href;
    const module = (await import(moduleUrl)) as {
      spellNameIndex?: Array<{
        slug: string;
        nameFolded?: string;
        nameNormalized?: string;
        name: string;
      }>;
    };
    const entries = module.spellNameIndex ?? [];
    for (const entry of entries) {
      const key = (
        entry.nameFolded ??
        entry.nameNormalized ??
        entry.name
      )
        .toLowerCase()
        .normalize('NFKD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/['â€™`]/g, '')
        .replace(/[^a-z0-9]+/g, ' ')
        .trim();
      if (key.length > 0) {
        output.set(key, entry.slug);
      }
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`[classes:build] Could not load spellNameIndex; spell slug refs will be best-effort only.\n${message}`);
  }

  return output;
};

const run = async (): Promise<void> => {
  const inputPath = resolveInputPath();
  if (!existsSync(inputPath)) {
    const lines: string[] = [];
    lines.push('[classes:build] Failed to build classes/subclasses pack.');
    lines.push(`CLASSES_TXT_PATH: ${envPathRaw ? envPathRaw : '(not set)'}`);
    lines.push(`Tried input path: ${inputPath}`);
    lines.push(`Fallback path: ${fallbackPath}`);
    lines.push(
      'Provide CLASSES_TXT_PATH or place dnd5e_classes_subclasses.txt at repository root.'
    );
    throw new Error(lines.join('\n'));
  }

  const rawText = readFileSync(inputPath, 'utf8');
  const spellSlugByName = await loadSpellSlugMap();
  const pack = buildClassesPackFromText(rawText, {
    spellSlugByName
  });

  mkdirSync(path.dirname(indexOutputPath), {
    recursive: true
  });
  mkdirSync(detailsOutputDir, {
    recursive: true
  });
  clearDirectoryJsonFiles(detailsOutputDir);

  for (const detail of pack.details) {
    const outputPath = path.resolve(detailsOutputDir, `${detail.id}.json`);
    writeFileSync(outputPath, JSON.stringify(detail, null, 2), 'utf8');
  }

  const banner =
    '// This file is auto-generated by apps/web/scripts/build-classes-pack.ts.\n' +
    '// Do not edit manually.\n\n';
  const source =
    `${banner}` +
    "import type { ClassesPackIndex } from '../types';\n\n" +
    `export const classesPackIndex: ClassesPackIndex = ${JSON.stringify(pack.index, null, 2)};\n`;
  writeFileSync(indexOutputPath, source, 'utf8');

  const classCount = pack.details.filter((entry) => entry.kind === 'CLASS').length;
  const subclassCount = pack.details.filter((entry) => entry.kind === 'SUBCLASS').length;

  console.log(`[classes:build] Built classes pack with ${pack.index.count} entries.`);
  console.log(`[classes:build] Classes: ${classCount}, Subclasses: ${subclassCount}`);
  console.log(`[classes:build] Input: ${inputPath}`);
  console.log(`[classes:build] Index output: ${indexOutputPath}`);
  console.log(`[classes:build] Detail output: ${detailsOutputDir}`);
};

void run().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(message);
  process.exit(1);
});

