import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildSpellsPackFromText } from '../src/rules/spells/parse/parseSpellsTxt';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '../../..');
const fallbackTxtPath = path.resolve(repoRoot, 'dnd5e_spells.txt');
const envPathRaw = process.env.SPELLS_TXT_PATH?.trim();
const envPath = envPathRaw ? path.resolve(envPathRaw) : null;

const resolveInputPath = (): string => {
  if (envPath) {
    return envPath;
  }

  return fallbackTxtPath;
};

const inputPath = resolveInputPath();

try {
  const txt = readFileSync(inputPath, 'utf8');
  const pack = buildSpellsPackFromText(txt);

  const outputPath = path.resolve(repoRoot, 'apps/web/src/rules/spells/generated/spellsPack.ts');
  const nameIndexPath = path.resolve(
    repoRoot,
    'apps/web/src/rules/spells/generated/spellNameIndex.ts'
  );
  mkdirSync(path.dirname(outputPath), {
    recursive: true
  });

  const banner =
    '// This file is auto-generated by apps/web/scripts/build-spells-pack.ts.\n' +
    '// Do not edit manually.\n\n';

  const source = `${banner}import type { SpellsPack } from '../types';\n\nexport const spellsPack: SpellsPack = ${JSON.stringify(
    pack,
    null,
    2
  )};\n`;

  writeFileSync(outputPath, source, 'utf8');

  const nameIndex = pack.metas
    .map((meta) => ({
      slug: meta.slug,
      name: meta.name,
      nameNormalized: meta.nameNormalized
    }))
    .sort((left, right) => left.name.localeCompare(right.name));

  const nameIndexSource = `${banner}import type { SpellNameIndexEntry } from '../types';\n\nexport const spellNameIndex: SpellNameIndexEntry[] = ${JSON.stringify(
    nameIndex,
    null,
    2
  )};\n`;
  writeFileSync(nameIndexPath, nameIndexSource, 'utf8');

  console.log(`[spells:build] Built spell pack with ${pack.count} spells.`);
  console.log(`[spells:build] Input: ${inputPath}`);
  console.log(`[spells:build] Output: ${outputPath}`);
  console.log(`[spells:build] Output: ${nameIndexPath}`);
  console.log(
    `[spells:build] Table restoration: restored ${pack.tableRestoration?.restored.length ?? 0}, unresolved ${pack.tableRestoration?.unresolvedCandidates.length ?? 0}`
  );
} catch (error) {
  const parts: string[] = [];
  parts.push('[spells:build] Failed to build spell pack.');
  parts.push(`SPELLS_TXT_PATH: ${envPathRaw ? envPathRaw : '(not set)'}`);
  parts.push(`Tried input path: ${inputPath}`);
  parts.push(`Fallback path: ${fallbackTxtPath}`);
  parts.push(
    'Provide SPELLS_TXT_PATH or place dnd5e_spells.txt at repository root (./dnd5e_spells.txt).'
  );

  const message = error instanceof Error ? error.message : String(error);
  parts.push(`Error: ${message}`);

  console.error(parts.join('\n'));
  process.exit(1);
}
