import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  buildLineagesPackFromContentEntries,
  type SourceLineageJson
} from '../src/rules/lineages/parse/parseLineagesContentJson';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '../../..');

const envDirRaw = process.env.LINEAGES_JSON_DIR?.trim();
const envDir = envDirRaw ? path.resolve(envDirRaw) : null;
const fallbackDir = path.resolve(repoRoot, 'content');

const indexOutputPath = path.resolve(repoRoot, 'apps/web/src/rules/lineages/generated/lineagesIndex.ts');
const detailsOutputDir = path.resolve(repoRoot, 'apps/web/public/rules/lineages/entries');

const resolveInputDir = (): string => {
  if (envDir) {
    return envDir;
  }

  return fallbackDir;
};

const clearDirectoryJsonFiles = (directoryPath: string): void => {
  if (!existsSync(directoryPath)) {
    return;
  }

  const entries = readdirSync(directoryPath, {
    withFileTypes: true
  });
  for (const entry of entries) {
    const fullPath = path.join(directoryPath, entry.name);
    if (entry.isDirectory()) {
      clearDirectoryJsonFiles(fullPath);
      continue;
    }

    if (entry.isFile() && entry.name.toLowerCase().endsWith('.json')) {
      rmSync(fullPath, {
        force: true
      });
    }
  }
};

const loadEntries = (inputDir: string): Array<{ fileName: string; payload: SourceLineageJson }> => {
  return readdirSync(inputDir)
    .filter((entry) => entry.toLowerCase().endsWith('.json') && entry.toLowerCase() !== '_index.json')
    .sort((left, right) => left.localeCompare(right))
    .map((fileName) => {
      const payload = JSON.parse(
        readFileSync(path.resolve(inputDir, fileName), 'utf8')
      ) as SourceLineageJson;
      return {
        fileName,
        payload
      };
    })
    .filter((entry) => entry.payload?.kind === 'LINEAGE' && Array.isArray(entry.payload.content?.tree));
};

const run = async (): Promise<void> => {
  const inputDir = resolveInputDir();
  if (!existsSync(inputDir)) {
    const lines: string[] = [];
    lines.push('[lineages:build] Failed to build lineages pack.');
    lines.push(`LINEAGES_JSON_DIR: ${envDirRaw ? envDirRaw : '(not set)'}`);
    lines.push(`Tried input dir: ${inputDir}`);
    lines.push(`Fallback dir: ${fallbackDir}`);
    lines.push('Provide LINEAGES_JSON_DIR or place lineage JSON files in ./content.');
    throw new Error(lines.join('\n'));
  }

  const entries = loadEntries(inputDir);
  if (entries.length === 0) {
    throw new Error(`[lineages:build] No valid LINEAGE JSON files found in ${inputDir}.`);
  }

  const pack = buildLineagesPackFromContentEntries(entries);

  mkdirSync(path.dirname(indexOutputPath), {
    recursive: true
  });
  mkdirSync(detailsOutputDir, {
    recursive: true
  });
  clearDirectoryJsonFiles(detailsOutputDir);

  for (const detail of pack.details) {
    const outputPath = path.resolve(detailsOutputDir, `${detail.id}.json`);
    writeFileSync(outputPath, JSON.stringify(detail, null, 2), 'utf8');
  }

  const banner =
    '// This file is auto-generated by apps/web/scripts/build-lineages-pack.ts.\n' +
    '// Do not edit manually.\n\n';
  const source =
    `${banner}` +
    "import type { LineagesPackIndex } from '../types';\n\n" +
    `export const lineagesPackIndex: LineagesPackIndex = ${JSON.stringify(pack.index, null, 2)};\n`;

  writeFileSync(indexOutputPath, source, 'utf8');

  console.log(`[lineages:build] Built lineages pack with ${pack.index.count} entries.`);
  console.log(`[lineages:build] Input dir: ${inputDir}`);
  console.log(`[lineages:build] Index output: ${indexOutputPath}`);
  console.log(`[lineages:build] Detail output: ${detailsOutputDir}`);
};

void run().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(message);
  process.exit(1);
});
